# Generated by Django 5.1.6 on 2025-02-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('experiment_name', models.CharField(max_length=100)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
